### ISSUE TITLE
can't start the examples

### ISSUE THREAD

**Issue by deden** [abhiaiyer91/apollo-storybook-decorator#18]
This repo is awesome.
I really want to try it. However, after cloning and run all commands (from Readme.md),
```
$ yarn # install node deps
$ lerna bootsrap
$ yarn storybook # for storybook testing
```
 always got error :
`/bin/sh: start-storybook: command not found`

btw, I have storybook in my global.

**Comment by abhiaiyer91** [comment]
Hey there! Let me write some updated instructions, sorry about this!
