### ISSUE TITLE
What about using graphql-js directly without apollo-test-utils?

### ISSUE THREAD

**Issue by xavcz** [abhiaiyer91/apollo-storybook-decorator#2]
Hey Abhi, thanks for making this decorator: you simplify the life of my team and mine 🎉 

👌 What's up now
---

When the GraphQL client is created, `mockNetworkInterfaceWithSchema` from `apollo-test-utils` is called so that every request will be validated directly against the (mocked) schema: https://github.com/abhiaiyer91/apollo-storybook-decorator/blob/master/src/index.js#L47

In the end, this function is just creating the `query` method used by the client and make it call `graphql` from `graphql-js` with the schema: https://github.com/apollographql/apollo-test-utils/blob/master/src/mocks/mockNetworkInterfaceWithSchema.ts#L15

We also have the ability to do complex mocking with `typeResolvers` which is pretty neat.

So far, so good!

🤙 What could be even more awesome
---
Taking in consideration that the use of `apollo-test-utils` is a really thin layer of abstraction on top of `graphql-js` with a fixed set of parameters (`contextValue` & `rootValue` set to `{}`)

What about creating a custom interface that calls `graphql` directly and allow for all its option?

So we could do things like
```js
apolloStorybookDecorator({
  typeDefs,
  mocks,
  context: {
    someModel: new SomeModel(),
  },
});
```

Would you be interested in such PR? Or should the decorator keep `apollo-test-utils` as a dependency and this issue moved there?

> ~I'm asking cause some of my mocks depends on a fake context, and that's pretty handy~ I actually worked around that with a closure around my mocks, but still it might be useful 😄

**Comment by abhiaiyer91** [comment]
@xavcz Sorry for not getting back to you sooner! I would definitely interested in this PR! Lets keep the api relatively backwards compatible and add more!!

**Comment by xavcz** [comment]
Dope, I'll go for that 👍
