### ISSUE TITLE
React Native Packager throws error because of `.babelrc` 

### ISSUE THREAD

**Issue by greyexpert** [abhiaiyer91/apollo-storybook-decorator#22]
Hey there,

React Native packager gives me an error when I try to use the library.

The error:
```
error: bundling failed: Error: Couldn't find preset "stage-0" relative to directory ".../node_modules/apollo-storybook-react-native"
```
The easiest solution would be to include `.babelrc` into `.npmignore`

Currently I remove the `.babelrc` in `postinstall`

**Comment by tonyxiao** [comment]
Having the same issue - my solution uses https://github.com/ds300/patch-package

**Comment by tonyxiao** [comment]
Actually that didn't work. I had to manually add `babel-preset-stage-0` and `graphql-tools` to `devDependencies` to get this to work.

**Comment by abhiaiyer91** [comment]
sorry guys ill fix this

**Comment by abhiaiyer91** [comment]
Updated all modules to only use preset-env

**Comment by petrbela** [comment]
I'm still getting this error, most likely because it's still present in the `core` module: https://github.com/abhiaiyer91/apollo-storybook-decorator/blob/master/packages/apollo-storybook-core/.babelrc#L7
