### ISSUE TITLE
Issues installing this package

### ISSUE THREAD

**Issue by hmontes** [abhiaiyer91/apollo-storybook-decorator#3]
Hi. 

I have several issues installing this package.

- First. Missing graphql-tools. Ok, Installed in the client (save-dev)
- Then. Missing apollo-test-utils. mmmm Ok, installed.
- Finally. Missing redux-logger....

So, Your package throws a lot of errors (Can't resolve ...). Can you fix this, please? It's a very good idea test a Apollo Graphql App with storyboook.

Thank you

**Comment by abhiaiyer91** [comment]
@hmontes thanks for the issue!

https://github.com/abhiaiyer91/apollo-storybook-decorator/blob/master/package.json#L41

These were intended to be Peer Dependencies, if you think they should be hard deps please make a PR! Would love to have the contribution.

**Comment by xavcz** [comment]
Maybe an addition in the README (like "as you use storybook & react-apollo together, you may want to add also graphql-tools for blabla and redux-logger for blabla) to tell people why they are intended to be peer deps?

**Comment by abhiaiyer91** [comment]
Yeah, I think thats the case. These definitely are meant to be peer deps!
