### ISSUE TITLE
disable "loading" state for snapshot testing

### ISSUE THREAD

**Issue by macrozone** [abhiaiyer91/apollo-storybook-decorator#36]
i use apollo-storybook-decorator together with jest and storyshots for snapshottesting. But the problem is, that these tests will alway snapshot while `loading:true`.

I tried to disable the delay, but with no luck. Any idea how i can wait for the data before snapshotting?

**Comment by abhiaiyer91** [comment]
Disabling the delay is our best bet, but I dont believe i expose any triggers for that. Let me look into it

**Comment by abhiaiyer91** [comment]
Oh okay, I forgot delayMs was an option to `apolloLinkOptions`

**Comment by macrozone** [comment]
@abhiaiyer91 Yeah, experimented with that, but there are several problems:

- delayMs= 0 will be set to 300, because 0 is falsy in js. So we have to use something like `typeof options.delayMs == "number" ? options.delayMs : 300`
- even with that change, loading is still true on first render, but i am unsure why. Maybe you have an idea? something in apollo-link that can be changed?

**Comment by abhiaiyer91** [comment]
Ah okay, i can make that change to delayMs

**Comment by abhiaiyer91** [comment]
Let me take a look at the loading thing, can i see the tests youre trying to write?

**Comment by williamboman** [comment]
`@apollo/react-testing` has a MockLink class that is probably easier to work with

**Comment by williamboman** [comment]
#128 doesn't really fix this issue. We're still only getting the loading state of queries in our snapshots, is there some extra configuration other than `delayMs: 0` required?
