### ISSUE TITLE
Must provide typeDefs - if typeDefs have been combined from multiple sources

### ISSUE THREAD

**Issue by pixelstew** [abhiaiyer91/apollo-storybook-decorator#44]
I have a fairly simple setup at the mo where I am adding the decorator as per the instructions

```
// .storybook/config.js
addDecorator(
  apolloStorybookDecorator({
    typeDefs,
    mocks,
  }),
);
```
All works well if I import typedefs from a single file but if I import them merged from different files, eg

```
import { typeDefs as mediaTypeDefs, mocks as mediaMocks } from './mocks/media';
import { typeDefs as fileUploadTypeDefs, mocks as fileUploadMocks } from './mocks/fileUpload';

export const queryRoot = gql`
  type Query {
    jobs: [Job]
    mediaList(uid: String): [Media]
    media(uid: String): Media
    uploads: [File]
  }

  type Mutation {
    uploadFiles(files: [Upload!]!): [File]!
  }

  schema {
    query: Query
    mutation: Mutation
  }
`;

export const typeDefs = [queryRoot, mediaTypeDefs, fileUploadTypeDefs];
```
I get a `Must include typeDefs` error.

I would like to split my schema into manageable chunks but this issue is holding that ambition back.

Any ideas?

Cheers

**Comment by abhiaiyer91** [comment]
Hey there! under the hood we pass typedefs to `makeExecutableSchema` which i dont believe accepts the GraphQL AST generated from `gql` tag. I think if they are an array of strings this will work as you posted.

**Comment by pixelstew** [comment]
Fantastic, hopefully that is all it was. I’ll try tonight.

**Comment by pixelstew** [comment]
Thanks for the heads up - all working now
