### ISSUE TITLE
@client schema support

### ISSUE THREAD

**Issue by austinamorusocfc** [abhiaiyer91/apollo-storybook-decorator#46]
Blanket noob question whats the magic sauce to get @client from https://github.com/apollographql/apollo-link-state to work?

**Comment by MarkTA** [comment]
+1 I have been trying to get this to work for a while now...

**Comment by austinamorusocfc** [comment]
https://github.com/abhiaiyer91/apollo-storybook-decorator/blob/587809bcbb075e8e7236abc5caf8f45bac32a88c/packages/apollo-storybook-react/example/.storybook/config.js

**Comment by abhiaiyer91** [comment]
Is this working for you all? Anything you need clarified?

**Comment by austinamorusocfc** [comment]
Nope thats working just fine. Now working through issues on react native storybook setup. Thanks for the prompt response. So far your library is a god send.

**Comment by abhiaiyer91** [comment]
No problem! and if you need any help let me know!

**Comment by austinamorusocfc** [comment]
I'm getting undefined is not an object (evaluating 'navigator.userAgent.length') But I'm assuming this is my code not yours.
