### ISSUE TITLE
Make compatible with apollo v2

### ISSUE THREAD

**Issue by crubier** [abhiaiyer91/apollo-storybook-decorator#6]

**Comment by abhiaiyer91** [comment]
Sure, will def tackle this soon! Or willing to take PRs!

**Comment by crubier** [comment]
You might be interested in https://github.com/apollographql/apollo-link/issues/66

**Comment by liz-mars** [comment]
Yes, please! This is now weirdly urgent -- had to bump to 2.0 to solve an unrelated issue, and now without my beloved storybook. ;_;

I'll ask my boss if I can throw some time at a PR

**Comment by abhiaiyer91** [comment]
@liz-mars @crubier thanks for reporting this! Its been a crazy week coming back from GraphQL Summit, will definitely try and get you an upgrade! If you can throw some time at a PR, AMAZING, if not will def try and do it this weekend

**Comment by liz-mars** [comment]
PR is sent :) Works for me. But I was sad to remove all that redux-related code because redux integration is no longer a thing in Apollo 2.

**Comment by abhiaiyer91** [comment]
`apollo-storybook-react@0.1.0` <- for the newest apollo client
