### ISSUE TITLE
Getting this working with react-apollo-hooks?

### ISSUE THREAD

**Issue by elie222** [abhiaiyer91/apollo-storybook-decorator#63]
Any recommendations to get this working with:
https://github.com/trojanowski/react-apollo-hooks?

**Comment by abhiaiyer91** [comment]
I will take a look at this today

**Comment by abhiaiyer91** [comment]
You can pass in a `Provider` to the decorator in version 0.2.1

```
    apolloStorybookDecorator({
      typeDefs,
      mocks,
      Provider: ApolloProviderFromHooksPackage // defaults to ApolloProvider
    }),
```

**Comment by elie222** [comment]
Ah thanks! Is it possible to pass in two providers? I may just pass in a
different provider where needed per story

**Comment by abhiaiyer91** [comment]
@elie222 unfortunately no! Passing it where needed is a good idea!
