### ISSUE TITLE
[vue] broken import

### ISSUE THREAD

**Issue by tsteenkamp** [abhiaiyer91/apollo-storybook-decorator#67]
```
import apolloStorybookDecorator from 'apollo-storybook-vue'
``` 

seems to be broken:

`Module not found: Error: Can't resolve 'apollo-storybook-vue' in ...`

import via absolute path works:

```
import apolloStorybookDecorator from '../node_modules/apollo-storybook-vue/lib/index'
```

I noticed that after installing the npm-package `node_modules/apollo-storybook-vue` has no subfolder `src` (in contrast to `node_modules/apollo-storybook-core`), so maybe the build/deployment pipeline is missing something.

**Comment by beep** [comment]
Same issue here.

**Comment by abhiaiyer91** [comment]
oh crap! so sorry about that!!! let me fix!

**Comment by beep** [comment]
Thanks, @abhiaiyer91! Weirdly, I’m still having the issue after upgrading to 0.0.3.
`import apolloStorybookDecorator from 'apollo-storybook-vue';` gives me the `Module not found` error; but this works just fine:

```
import apolloStorybookDecorator from '../../../node_modules/apollo-storybook-vue/lib/';
```

Is it working for you?

**Comment by abhiaiyer91** [comment]
My apologies @beep ! I forgot to add a `main` in package.json DUH. 0.0.4 is out!

**Comment by beep** [comment]
That did it! Thank you so much, @abhiaiyer91!
