### ISSUE TITLE
Support apollo hooks 

### ISSUE THREAD

**Issue by Jaikant** [abhiaiyer91/apollo-storybook-decorator#72]
The imports in the latest apollo hooks is a little [different](https://www.apollographql.com/docs/react/hooks-migration/). The package needs to be migrated to support this.

**Comment by Kamilius** [comment]
@abhiaiyer91 Hi, could you tell when related PR will be reviewed/merged? Thanks

**Comment by dcstone09** [comment]
@Kamilius just was, this issue can be closed now 👍

**Comment by abhiaiyer91** [comment]
Thank you @dcstone09

**Comment by Kamilius** [comment]
Sadly this PR haven't solved my issue.
Storybook's still telling me that it can't find a valid apollo `client`

**Comment by dcstone09** [comment]
@kamilius I'll review this today

**Comment by dcstone09** [comment]
@Kamilius The examples in the repo are working and the configuration process didn't change. Can you open an issue with your configuration or a small reproducible example?

**Comment by mgan59** [comment]
Previously my stories were focused on lower-level components and I'd made the move to react-hooks-apollo a few weeks back.  Made an attempt to write a story for a component that used `useQuery` which is what led me to this package for a decorator. 

I installed the package the default setup this throwing this error

For: `@storybook/react v5.2.5`

```shell
ERROR in ./node_modules/apollo-storybook-core/lib/index.js
Module not found: Error: Can't resolve 'graphql-tools' in '/project/node_modules/apollo-storybook-core/lib'
 @ ./node_modules/apollo-storybook-core/lib/index.js 15:20-44
 @ ./node_modules/apollo-storybook-react/lib/index.js
```

This is my Story

```javascript

# mycomponent.stories.js
import React from 'react'
import StoryRouter from 'storybook-react-router'
import MyComponent from './MyComponent'
import apolloStorybookDecorator from "apollo-storybook-react";

export default {
  title: 'MyComponent',

  parameters: {
    component: MyComponent,
    componentSubtitle: '',
  },
  decorators: [
    apolloStorybookDecorator()
  ]
}

export const base = () => (
  <MyComponent />
)
```

Thoughts? 😄

**Comment by glenp01** [comment]
@abhiaiyer91  @dcstone09 , npm doesn't have the latest version of the packages which is why hooks is still failing. Could you publish it please?

**Comment by snymanth** [comment]
@dcstone09 @abhiaiyer91 
Any update on this? Is the latest version published yet?

**Comment by lessenadam** [comment]
@dcstone09 @abhiaiyer91 bump?

**Comment by dcstone09** [comment]
@glenp01 @snymanth @lessenadam Sorry for the late reply, I got the notification and I'll review this tonight!

**Comment by zerocewl** [comment]
@dcstone09 @abhiaiyer91
still an issue?!
any workaround here?

```
ERROR in ./node_modules/apollo-storybook-core/lib/index.js
Module not found: Error: Can't resolve 'graphql-tools' in './projects/frontend/node_modules/apollo-storybook-core/lib'
 @ ./node_modules/apollo-storybook-core/lib/index.js 15:20-44
 @ ./node_modules/apollo-storybook-react/lib/index.js
```
